/** Design system: Software Almanac — the company narrative remains editorial while showcasing a current registry product. */
import { ArrowUpRight, Asterisk, Check } from "lucide-react";
import { Link } from "wouter";
import RegistryProductVisual from "@/components/RegistryProductVisual";
import SiteShell, { BrandMark } from "@/components/SiteShell";
import { trpc } from "@/lib/trpc";

export default function About() {
  const productsQuery = trpc.registry.public.list.useQuery();
  const contentQuery = trpc.registry.public.siteContent.useQuery();
  const product = productsQuery.data?.[0];
  const statement = contentQuery.data?.find((item) => item.key === "about.statement")?.value;
  return <SiteShell><main className="about-page"><section className="page-hero about-hero"><div><span className="section-label"><i /> About the collective</span><h1>Independent by design.<br /><em>Useful by default.</em></h1></div><div className="about-intro-side"><BrandMark /><p>We make software products for the decisions, routines, and creative work that deserve more care than a generic tool can give.</p></div></section><section className="about-statement"><span>[ OUR BELIEF ]</span><p>{statement ?? "Loading the workshop point of view."}</p><div className="statement-rule" /></section><section className="about-grid"><div className="about-grid-copy"><span className="section-label"><i /> What we are building for</span><h2>Work that feels<br /><em>more considered.</em></h2><p>Workshop Collective is an independent software product company. We care about the operations behind a team, the logic behind a decision, and the creative rhythm behind a published idea.</p><p>We stay deliberately focused: build useful software, solve real problems, and keep things simple enough that people want to return to it.</p></div><div className="about-grid-visual"><span className="visual-index">[ a system with room to think ]</span>{product && <RegistryProductVisual product={product} alt={`${product.name} product preview`} />}<span className="about-annotation">We make the invisible work<br />a little more visible.</span></div></section><section className="values-section"><div className="values-title"><span className="section-label"><i /> How we work</span><h2>Small principles.<br /><em>Lasting impact.</em></h2></div><div className="values-list">{[{ title: "Real before remarkable", copy: "We prefer a product that removes a daily obstacle over a clever idea that does not survive the week." }, { title: "Context is part of the interface", copy: "Every screen should help people understand why something matters—not just what to click next." }, { title: "Craft lives in the details", copy: "Clarity comes from dozens of small decisions: a word, a state, a hand-off, a well-placed rule." }].map((value, index) => <article key={value.title}><span>0{index + 1}</span><div><h3>{value.title}</h3><p>{value.copy}</p></div><Asterisk size={17} /></article>)}</div></section><section className="about-cta"><div><span>Build useful software.</span><span>Solve real problems.</span><span>Keep things simple.</span></div><Link href="/contact" className="button button-light">Work with us <ArrowUpRight size={17} /></Link><Check className="about-check" size={30} /></section></main></SiteShell>;
}
