/** CMS access gate: OAuth begins from a considered editorial entry screen, while the server remains the authority for every administrator action. */
import type { ReactNode } from "react";
import { ArrowUpRight, ChevronRight, LockKeyhole, ShieldAlert, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { startLogin } from "@/const";
import DashboardLayout from "@/components/DashboardLayout";
import { BrandMark } from "@/components/SiteShell";
import { useAuth } from "@/_core/hooks/useAuth";

function AccessFrame({ eyebrow, title, body, children, denied = false }: { eyebrow: string; title: ReactNode; body: string; children: ReactNode; denied?: boolean }) {
  return <main className="min-h-screen overflow-hidden bg-[#f6f0e6] text-[#102239]"><div className="grid min-h-screen lg:grid-cols-[.92fr_1.08fr]"><section className="relative flex min-h-[44vh] flex-col justify-between overflow-hidden bg-[#102239] px-7 py-8 text-[#f8f4ea] sm:px-12 sm:py-12"><div className="absolute -right-24 -top-28 h-80 w-80 rounded-full border border-white/15" /><div className="absolute -bottom-28 -left-24 h-80 w-80 rounded-full border border-[#f05a43]/60" /><div className="relative flex items-center justify-between"><Link href="/" className="inline-flex items-center gap-3 text-[#f8f4ea]"><span className="grid h-9 w-9 place-items-center border border-white/25"><BrandMark /></span><span><b className="block font-[DM_Serif_Display] text-xl leading-none">Workshop</b><small className="mt-1 block text-[9px] font-extrabold uppercase tracking-[.16em] text-white/60">Collective CMS</small></span></Link><span className="text-[10px] font-extrabold uppercase tracking-[.16em] text-white/50">Admin access</span></div><div className="relative max-w-md py-12 lg:py-0"><span className="mb-5 inline-flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-[.17em] text-[#ff826e]"><Sparkles size={13} /> Independent software, considered</span><p className="font-[DM_Serif_Display] text-4xl leading-[.95] sm:text-6xl">The calm side<br />of <em className="text-[#ff826e]">keeping work</em><br />in motion.</p></div><div className="relative flex items-end justify-between border-t border-white/15 pt-5 text-xs leading-5 text-white/60"><span>Product Registry<br />Site content<br />Access control</span><span className="text-right">A private workspace<br />for considered publishing.</span></div></section><section className="relative flex items-center px-7 py-10 sm:px-14 lg:px-20"><div className="absolute right-8 top-8 text-[10px] font-extrabold uppercase tracking-[.15em] text-slate-400">[ secure sign-in ]</div><div className="w-full max-w-xl"><span className={`inline-flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-[.16em] ${denied ? "text-[#c44735]" : "text-[#f05a43]"}`}>{denied ? <ShieldAlert size={14} /> : <LockKeyhole size={14} />}{eyebrow}</span><h1 className="mt-5 font-[DM_Serif_Display] text-5xl leading-[.94] tracking-tight text-[#102239] sm:text-6xl">{title}</h1><p className="mt-6 max-w-lg text-base leading-7 text-slate-600">{body}</p><div className="mt-9">{children}</div><div className="mt-12 grid gap-3 border-t border-slate-900/15 pt-5 text-xs leading-5 text-slate-500 sm:grid-cols-2"><span className="flex gap-2"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-[#4d7c5a]" />Role checks run on the server for every CMS action.</span><span className="flex gap-2"><LockKeyhole className="mt-0.5 h-4 w-4 shrink-0 text-[#4d7c5a]" />Your session is verified before product or user data is available.</span></div></div></section></div></main>;
}

export default function AdminGuard({ children }: { children: ReactNode }) {
  const { user, loading } = useAuth();
  if (loading) return <main className="grid min-h-screen place-items-center bg-[#f6f0e6]"><div className="text-center"><span className="inline-block h-8 w-8 animate-spin rounded-full border-2 border-[#102239]/20 border-t-[#f05a43]" /><p className="mt-4 text-xs font-extrabold uppercase tracking-[.16em] text-[#102239]">Opening the CMS</p></div></main>;
  if (!user) return <AccessFrame eyebrow="Workshop CMS" title={<>A private place<br />to keep the <em className="text-[#f05a43]">work clear.</em></>} body="Sign in with the account configured as the project owner or one that an existing administrator has approved. Your identity is verified before the CMS opens."><button type="button" onClick={() => startLogin()} className="group inline-flex items-center gap-3 bg-[#102239] px-5 py-4 text-sm font-extrabold text-[#fffdf8] transition-transform duration-150 hover:-translate-y-0.5 active:scale-[.97]">Continue securely <ArrowUpRight className="h-4 w-4 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></button><p className="mt-4 text-xs text-slate-500">First time here? Sign in once with the project-owner account to initialize access.</p>{import.meta.env.DEV ? <div className="mt-6 border-t border-[#102239]/10 pt-5"><p className="text-[10px] font-extrabold uppercase tracking-[.15em] text-slate-400">[ local development ]</p><div className="mt-3 flex flex-wrap items-center gap-3"><a href="/api/auth/local-signin?role=admin" className="inline-flex items-center gap-2 border border-[#f05a43] bg-[#f05a43]/10 px-4 py-2.5 text-xs font-extrabold uppercase tracking-wide text-[#c23a28] transition-transform duration-150 hover:-translate-y-0.5 active:scale-[.97]">Sign in as local admin</a><a href="/api/auth/local-signin?role=user" className="inline-flex items-center gap-2 border border-[#102239]/30 px-4 py-2.5 text-xs font-extrabold uppercase tracking-wide text-[#102239] transition-transform duration-150 hover:-translate-y-0.5 active:scale-[.97]">Sign in as standard user</a></div></div> : null}</AccessFrame>;
  if (user.role !== "admin") return <AccessFrame denied eyebrow="Access needs approval" title={<>Your account is<br />signed in, but <em className="text-[#f05a43]">not approved.</em></>} body="The CMS recognizes your identity but your account does not hold an administrator role. Ask an existing administrator to open User Management and approve access for this account."><Link href="/" className="group inline-flex items-center gap-3 border border-[#102239] px-5 py-4 text-sm font-extrabold text-[#102239] transition-transform duration-150 hover:-translate-y-0.5 active:scale-[.97]">Return to the website <ChevronRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" /></Link><p className="mt-4 text-xs text-slate-500">For recovery, the configured project owner always remains eligible for administrator access.</p></AccessFrame>;
  return <DashboardLayout>{children}</DashboardLayout>;
}
