/** Design system: Software Almanac — contact framing uses editable registry content while retaining a concise, high-trust inquiry flow. */
import { type FormEvent } from "react";
import { ArrowUpRight, Mail, MapPin } from "lucide-react";
import SiteShell from "@/components/SiteShell";
import { trpc } from "@/lib/trpc";

export default function Contact() {
  const contentQuery = trpc.registry.public.siteContent.useQuery();
  const intro = contentQuery.data?.find((item) => item.key === "contact.intro")?.value;
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const subject = encodeURIComponent(`Workshop Collective inquiry — ${String(data.get("company") || data.get("name"))}`); const body = encodeURIComponent(`Name: ${data.get("name")}\nEmail: ${data.get("email")}\nCompany: ${data.get("company")}\n\nMessage:\n${data.get("message")}`); window.location.href = `mailto:hello@workshopcollective.co?subject=${subject}&body=${body}`; };
  return <SiteShell><main className="contact-page"><section className="contact-hero"><div><span className="section-label"><i /> Contact</span><h1>Tell us what you are<br /><em>trying to make simpler.</em></h1></div><p>{intro ?? "Loading contact information."}</p></section><section className="contact-body"><aside className="contact-aside"><div><span>Write to us</span><a href="mailto:hello@workshopcollective.co"><Mail size={16} /> hello@workshopcollective.co <ArrowUpRight size={14} /></a></div><div><span>Based in</span><p><MapPin size={16} /> Jakarta, Indonesia<br />Working across time zones.</p></div><div className="contact-aside-note"><i /> The best starting point is the real problem, not a perfect brief.</div></aside><form className="contact-form" onSubmit={handleSubmit}><div className="form-heading"><span>01 / Your note</span><p>Fill in the essentials. Your mail app will open with the message ready to send.</p></div><label>Name<input required name="name" autoComplete="name" placeholder="Your name" /></label><label>Email<input required type="email" name="email" autoComplete="email" placeholder="you@company.com" /></label><label>Company <span>(optional)</span><input name="company" autoComplete="organization" placeholder="Company or team" /></label><label>What can we help with?<textarea required name="message" rows={5} placeholder="A product inquiry, partnership thought, or a workflow you would like to improve." /></label><button className="button button-ink" type="submit">Prepare email <ArrowUpRight size={17} /></button></form></section></main></SiteShell>;
}
