/** Product Registry seed: initial Workshop Collective portfolio is written once into the database, then managed only through the CMS. */
import type { InsertProduct } from "../drizzle/schema";

export const registryProductSeed: InsertProduct[] = [
  { id: "product_hris", name: "HRIS", slug: "hris", shortDescription: "Semua hal yang membuat operasi HR tersusun, terlihat, dan mudah ditindaklanjuti.", fullDescription: "Satu tempat yang tenang untuk data karyawan, kehadiran, cuti, payroll, dan dokumen operasional.", heroHeadline: "People operations that stay in view.", problem: "Saat data karyawan hidup di spreadsheet terpisah, pekerjaan HR menjadi pekerjaan mencari, memeriksa, lalu mengulang. Detail penting mudah tertinggal tepat ketika tim membutuhkannya.", solution: "HRIS menyatukan ritme kerja HR ke dalam satu alur yang dapat dibaca siapa pun yang diberi akses—tanpa memaksa tim mengubah cara kerja menjadi rumit.", outcome: "Lebih sedikit pengecekan manual. Lebih banyak kepastian dalam setiap keputusan operasional.", category: "People operations", productStatus: "active", publicationStatus: "published", capabilities: ["Employee records", "Attendance & leave", "Payroll checks", "Files & documents"], targetUsers: "Tim HR dan people operations yang ingin menjalankan administrasi dengan lebih rapi, tanpa kehilangan konteks manusianya.", demoUrl: null, workflowSteps: [{ title: "Rapikan data", copy: "Satukan profil, dokumen, dan riwayat penting karyawan." }, { title: "Jalankan rutinitas", copy: "Kelola kehadiran, cuti, dan pengecekan payroll dalam alur yang sama." }, { title: "Tindak lanjuti", copy: "Lihat hal yang membutuhkan perhatian sebelum menjadi pekerjaan tambahan." }], featured: 1, displayOrder: 1 },
  { id: "product_remuneration", name: "Remuneration", slug: "remuneration", shortDescription: "Perhitungan dan alokasi remuneration yang dapat dipercaya, dijelaskan, dan dilacak.", fullDescription: "Membantu tim mengelola performance pool, alokasi, approval, hingga publikasi dengan jejak keputusan yang jelas.", heroHeadline: "Clarity for decisions that matter.", problem: "Keputusan remunerasi menuntut ketelitian dan kepercayaan. Ketika logika perhitungan tersebar di banyak file, diskusi mudah berubah menjadi perdebatan versi.", solution: "Remuneration mengubah proses yang sensitif menjadi alur bersama: hitung, alokasikan, tinjau, setujui, lalu publikasikan dengan konteks yang tetap utuh.", outcome: "Keputusan yang lebih transparan—dan proses yang lebih ringan untuk dijelaskan kembali.", category: "Decision workflows", productStatus: "active", publicationStatus: "published", capabilities: ["Performance pools", "Allocation logic", "Approval routes", "Publication records"], targetUsers: "Tim HR, finance, dan leadership yang perlu memastikan setiap alokasi dipahami dan dapat ditelusuri.", demoUrl: null, workflowSteps: [{ title: "Susun pool", copy: "Bentuk dasar perhitungan sesuai kebijakan dan periode yang berlaku." }, { title: "Lihat alokasi", copy: "Tinjau distribusi dalam konteks orang, tim, dan keputusan yang mendasarinya." }, { title: "Publikasikan dengan jelas", copy: "Kunci hasil setelah approval dan simpan jejak prosesnya." }], featured: 1, displayOrder: 2 },
  { id: "product_ticketing", name: "Ticketing", slug: "ticketing", shortDescription: "Satu alur kerja dari feature sampai release—tanpa memutus hubungan antar pekerjaan.", fullDescription: "Platform ticketing dan work management untuk menghubungkan feature, task, subtask, development, testing, dan release.", heroHeadline: "Work moves better when the thread stays intact.", problem: "Pekerjaan produk sering kehilangan alur saat konteks berpindah dari diskusi, ke task, ke testing, lalu ke release. Yang tersisa hanya daftar tugas tanpa cerita.", solution: "Ticketing menjaga hubungan antar pekerjaan tetap terlihat. Tim dapat bergerak dari arah besar menuju detail kecil, lalu kembali melihat dampaknya pada release.", outcome: "Lebih sedikit status meeting. Lebih banyak pekerjaan yang maju dengan konteks yang sama.", category: "Work management", productStatus: "active", publicationStatus: "published", capabilities: ["Feature to subtask", "Development activity", "Testing progress", "Release tracking"], targetUsers: "Product, engineering, QA, dan delivery teams yang ingin bekerja dalam satu bahasa tanpa mengorbankan detail.", demoUrl: null, workflowSteps: [{ title: "Tetapkan arah", copy: "Mulai dari feature dan hasil yang ingin dicapai, bukan dari daftar task yang lepas." }, { title: "Pecah dengan konteks", copy: "Turunkan pekerjaan ke task dan subtask sambil mempertahankan hubungan asalnya." }, { title: "Antar sampai release", copy: "Ikuti status development, testing, dan release sebagai satu jalur kerja." }], featured: 1, displayOrder: 3 },
  { id: "product_reportforge", name: "ReportForge", slug: "reportforge", shortDescription: "Dokumen dan report berulang yang disusun sebagai sistem, bukan dirakit ulang setiap saat.", fullDescription: "Reusable templates dan rendering engine untuk menghasilkan dokumen yang terstruktur, konsisten, dan siap dipakai.", heroHeadline: "Make the repeatable feel effortless.", problem: "Report penting kerap berulang—namun prosesnya tetap dimulai dari salin-tempel, format ulang, dan pemeriksaan kecil yang memakan waktu.", solution: "ReportForge menjadikan struktur dokumen sebagai template yang dapat digunakan kembali, sementara data dan output dapat berubah sesuai kebutuhan.", outcome: "Waktu pembuatan yang lebih singkat dan dokumen yang tetap konsisten saat skala kerja bertambah.", category: "Document systems", productStatus: "active", publicationStatus: "published", capabilities: ["Reusable templates", "Structured fields", "Render workflows", "Output consistency"], targetUsers: "Tim operasional, finance, dan product yang menghasilkan report atau dokumen terstruktur secara berulang.", demoUrl: null, workflowSteps: [{ title: "Bangun sekali", copy: "Tentukan struktur, blok konten, dan field yang akan selalu dipakai." }, { title: "Gunakan kembali", copy: "Masukkan data yang relevan tanpa mengulang proses layout dan format." }, { title: "Render dengan yakin", copy: "Hasilkan output yang konsisten setiap kali dokumen dibutuhkan." }], featured: 0, displayOrder: 4 },
  { id: "product_kontenjadi", name: "KontenJadi", slug: "kontenjadi", shortDescription: "Satu workspace untuk membawa ide menjadi konten yang siap dipublikasikan dan didistribusikan.", fullDescription: "KontenJadi menyatukan seluruh alur creator: Idea → Direction → Script → Content Production → Video → Publish → Distribution.", heroHeadline: "One clear path from spark to publish.", problem: "Creator berpindah-pindah tool untuk mencari ide, menyusun arah, menulis skrip, menyiapkan aset, dan mempublikasikan konten. Alur menjadi putus, energi habis di perpindahan.", solution: "KontenJadi merangkai proses tersebut sebagai satu workspace end-to-end—agar waktu kreatif dipakai untuk membuat keputusan yang lebih baik, bukan mengelola tool yang terpisah.", outcome: "Dari ide sampai distribusi, setiap langkah memiliki arah dan tetap tersambung.", category: "Creator workflow", productStatus: "active", publicationStatus: "published", capabilities: ["Idea discovery", "Content direction", "Script creation", "Publish & distribution"], targetUsers: "Creator dan content teams yang ingin membuat lebih konsisten tanpa menambah tumpukan tools.", demoUrl: null, workflowSteps: [{ title: "Cari ide", copy: "Temukan benang merah yang layak dikembangkan dari insight dan referensi." }, { title: "Pilih arah", copy: "Tentukan sudut cerita, format, dan pesan sebelum produksi dimulai." }, { title: "Susun skrip", copy: "Rangkai struktur yang menjaga konten tetap fokus dan mudah dieksekusi." }, { title: "Siapkan konten", copy: "Kumpulkan aset, susun produksi, dan arahkan video dalam workspace yang sama." }, { title: "Publish", copy: "Siapkan materi final dengan detail yang siap ditayangkan." }, { title: "Distribute", copy: "Bawa konten ke kanal yang relevan tanpa kehilangan konteks asalnya." }], featured: 1, displayOrder: 5 },
];

export const siteContentSeed = [
  { key: "home.heroEyebrow", label: "Home — Hero eyebrow", value: "Independent software products" },
  { key: "home.heroTitle", label: "Home — Hero title", value: "Work gets lighter when the system makes sense." },
  { key: "home.heroDescription", label: "Home — Hero description", value: "We build calm, useful software for teams and creators who have real work to move through." },
  { key: "home.featuredHeading", label: "Home — Featured products heading", value: "Built around the messy middle of work." },
  { key: "about.statement", label: "About — Statement", value: "Software has the most value when it gives people back their attention." },
  { key: "contact.intro", label: "Contact — Intro", value: "Whether you are exploring one of our products, considering a partnership, or working through a business software need—we would like to hear the shape of it." },
];
