/** CMS shell: preserve the provided authenticated sidebar structure while presenting focused Product Registry and site-copy destinations. */
import { useAuth } from "@/_core/hooks/useAuth";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Sidebar, SidebarContent, SidebarFooter, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger, useSidebar } from "@/components/ui/sidebar";
import { startLogin } from "@/const";
import { useIsMobile } from "@/hooks/useMobile";
import { Boxes, ExternalLink, FileText, LayoutDashboard, LogOut, PanelLeft, UsersRound } from "lucide-react";
import { CSSProperties, useEffect, useRef, useState } from "react";
import { useLocation } from "wouter";
import { DashboardLayoutSkeleton } from "./DashboardLayoutSkeleton";
import { Button } from "./ui/button";

const menuItems = [{ icon: LayoutDashboard, label: "Overview", path: "/admin" }, { icon: Boxes, label: "Product Registry", path: "/admin/products" }, { icon: FileText, label: "Site Copy", path: "/admin/content" }, { icon: UsersRound, label: "User Management", path: "/admin/users" }, { icon: ExternalLink, label: "Public Website", path: "/" }];
const SIDEBAR_WIDTH_KEY = "workshop-cms-sidebar-width"; const DEFAULT_WIDTH = 270; const MIN_WIDTH = 220; const MAX_WIDTH = 380;

export default function DashboardLayout({ children }: { children: React.ReactNode }) { const [sidebarWidth, setSidebarWidth] = useState(() => Number(localStorage.getItem(SIDEBAR_WIDTH_KEY)) || DEFAULT_WIDTH); const { loading, user } = useAuth(); useEffect(() => localStorage.setItem(SIDEBAR_WIDTH_KEY, String(sidebarWidth)), [sidebarWidth]); if (loading) return <DashboardLayoutSkeleton />; if (!user) return <div className="flex min-h-screen items-center justify-center"><div className="max-w-md p-8 text-center"><h1 className="text-2xl font-semibold">Sign in to continue</h1><p className="mt-3 text-sm text-muted-foreground">Access to this workspace requires authentication.</p><Button onClick={() => startLogin()} size="lg" className="mt-6 w-full">Sign in</Button></div></div>; return <SidebarProvider style={{ "--sidebar-width": `${sidebarWidth}px` } as CSSProperties}><DashboardLayoutContent setSidebarWidth={setSidebarWidth}>{children}</DashboardLayoutContent></SidebarProvider>; }
function DashboardLayoutContent({ children, setSidebarWidth }: { children: React.ReactNode; setSidebarWidth: (width: number) => void }) { const { user, logout } = useAuth(); const [location, setLocation] = useLocation(); const { state, toggleSidebar } = useSidebar(); const isCollapsed = state === "collapsed"; const [isResizing, setIsResizing] = useState(false); const sidebarRef = useRef<HTMLDivElement>(null); const isMobile = useIsMobile(); const activeMenuItem = menuItems.find((item) => item.path === location || (item.path === "/admin/products" && location.startsWith("/admin/products")));
  useEffect(() => { const move = (event: MouseEvent) => { if (!isResizing) return; const left = sidebarRef.current?.getBoundingClientRect().left ?? 0; const width = event.clientX - left; if (width >= MIN_WIDTH && width <= MAX_WIDTH) setSidebarWidth(width); }; const up = () => setIsResizing(false); if (isResizing) { document.addEventListener("mousemove", move); document.addEventListener("mouseup", up); document.body.style.cursor = "col-resize"; } return () => { document.removeEventListener("mousemove", move); document.removeEventListener("mouseup", up); document.body.style.cursor = ""; }; }, [isResizing, setSidebarWidth]);
  return <><div className="relative" ref={sidebarRef}><Sidebar collapsible="icon" className="border-r-0"><SidebarHeader className="h-20 justify-center"><div className="flex items-center gap-3 px-3"><button onClick={toggleSidebar} className="grid h-8 w-8 place-items-center rounded-lg hover:bg-accent" aria-label="Toggle navigation"><PanelLeft className="h-4 w-4 text-muted-foreground" /></button>{!isCollapsed && <div><span className="block font-[DM_Serif_Display] text-lg leading-none tracking-tight">Workshop CMS</span><span className="mt-1 block text-[9px] font-extrabold uppercase tracking-[.14em] text-muted-foreground">Product publishing</span></div>}</div></SidebarHeader><SidebarContent><SidebarMenu className="px-2 py-2">{menuItems.map((item) => <SidebarMenuItem key={item.path}><SidebarMenuButton isActive={activeMenuItem?.path === item.path} onClick={() => setLocation(item.path)} tooltip={item.label} className="h-11"><item.icon className="h-4 w-4" /><span>{item.label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter className="p-3"><DropdownMenu><DropdownMenuTrigger asChild><button className="flex w-full items-center gap-3 rounded-lg px-1 py-1 text-left hover:bg-accent/50"><Avatar className="h-9 w-9 border"><AvatarFallback className="text-xs font-medium">{user?.name?.charAt(0).toUpperCase()}</AvatarFallback></Avatar>{!isCollapsed && <div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{user?.name || "Admin"}</p><p className="mt-1 truncate text-xs text-muted-foreground">{user?.email || "Project owner"}</p></div>}</button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-48"><DropdownMenuItem onClick={logout} className="text-destructive"><LogOut className="mr-2 h-4 w-4" />Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></SidebarFooter></Sidebar><div className={`absolute right-0 top-0 h-full w-1 cursor-col-resize hover:bg-primary/20 ${isCollapsed ? "hidden" : ""}`} onMouseDown={() => setIsResizing(true)} style={{ zIndex: 50 }} /></div><SidebarInset className="bg-[#f6f0e6]">{isMobile && <div className="sticky top-0 z-40 flex h-14 items-center border-b bg-[#f6f0e6]/95 px-2 backdrop-blur"><SidebarTrigger className="h-9 w-9 rounded-lg" /><span className="ml-2 text-sm font-bold">{activeMenuItem?.label ?? "CMS"}</span></div>}<main className="min-h-screen flex-1 p-5 md:p-8">{children}</main></SidebarInset></>; }
